import {
  IconLayoutDashboard, IconShoppingCart, IconUsers, IconFileInvoice,
  IconIdBadge2, IconWash, IconChartBar, IconSettings, IconDoorExit,
  IconCash, IconShoppingBag, IconCheckbox, IconBasket, IconHome,
  IconReceipt, IconCreditCard, IconBriefcase, IconTag, IconUser,
  IconCalendar, IconBell, IconPackage, IconCheck,
  IconX, IconEdit, IconTrash, IconEye, IconPhone, IconMail,
  IconMapPin, IconClock, IconTruck, IconBuildingStore, IconPrinter,
  IconCurrencyDollar, IconClipboard, IconSearch, IconNotes,
  IconMessage, IconStar, IconChartLine, IconBolt,
  IconFlame, IconCar, IconMoneybag, IconDiamond, IconDeviceMobile,
  IconSend, IconHourglass, IconRefresh, IconPlus, IconMenu2, IconShirt,
  IconBuilding, IconMan, IconTie, IconJacket, IconShoe,
  IconHelpCircle, IconLock, IconWorld, IconMoodSad, IconRobot,
  IconGift, IconConfetti, IconTarget, IconScale,
  IconBellOff, IconCopyright, IconCircle,
} from "@tabler/icons-react";

const icons = {
  dashboard: IconLayoutDashboard,
  shoppingCart: IconShoppingCart,
  users: IconUsers,
  fileInvoice: IconFileInvoice,
  idBadge2: IconIdBadge2,
  wash: IconWash,
  chartBar: IconChartBar,
  settings: IconSettings,
  doorExit: IconDoorExit,
  cash: IconCash,
  shoppingBag: IconShoppingBag,
  checkbox: IconCheckbox,
  basket: IconBasket,
  home: IconHome,
  receipt: IconReceipt,
  creditCard: IconCreditCard,
  briefcase: IconBriefcase,
  tag: IconTag,
  user: IconUser,
  tshirt: IconShirt,
  calendar: IconCalendar,
  bell: IconBell,
  package: IconPackage,
  check: IconCheck,
  x: IconX,
  edit: IconEdit,
  trash: IconTrash,
  eye: IconEye,
  phone: IconPhone,
  mail: IconMail,
  mapPin: IconMapPin,
  clock: IconClock,
  truck: IconTruck,
  buildingStore: IconBuildingStore,
  printer: IconPrinter,
  currencyDollar: IconCurrencyDollar,
  clipboard: IconClipboard,
  search: IconSearch,
  notes: IconNotes,
  message: IconMessage,
  star: IconStar,
  chartLine: IconChartLine,
  wave: IconShirt,
  bolt: IconBolt,
  flame: IconFlame,
  car: IconCar,
  moneybag: IconMoneybag,
  diamond: IconDiamond,
  deviceMobile: IconDeviceMobile,
  send: IconSend,
  hourglass: IconHourglass,
  refresh: IconRefresh,
  plus: IconPlus,
  menu2: IconMenu2,
  building: IconBuilding,
  man: IconMan,
  tie: IconTie,
  jacket: IconJacket,
  shoe: IconShoe,
  yarn: IconCircle,
  helpCircle: IconHelpCircle,
  lock: IconLock,
  world: IconWorld,
  moodSad: IconMoodSad,
  robot: IconRobot,
  gift: IconGift,
  confetti: IconConfetti,
  target: IconTarget,
  moodSport: IconTarget,
  scale: IconScale,
  bellOff: IconBellOff,
  copyright: IconCopyright,
  circle: IconCircle,
  jeans: IconShirt,
};

export default function Icon({ name, size = 20, stroke = 1.5, className, style, ...props }) {
  const Comp = icons[name];
  if (!Comp) return null;
  return <Comp size={size} stroke={stroke} className={className} style={{ display: "inline-block", verticalAlign: "middle", ...style }} {...props} />;
}

export { icons };
